### PR TITLE
a better README.md

### PR DESCRIPTION
**Pull request by drhgames**
I added a verb

### CODE REVIEW

**Comment by drhgames** [comment]
Hey do you like the changes?

**Comment by kh4science** [comment]
Yes. I like the changes.

**Comment by kh4science** [comment]
Did we get it to work?

**Comment by drhgames** [comment]
Feels good

**Comment by drhgames** [comment]
Ok then I'm going to merge.  3...2...1...

**Comment by drhgames** [comment]
Survivors Ready?  We are merged

**Pull request merged**
